server:
  port: 0

spring:
  datasource:
    url: ${INVENTORY_DB_URL:jdbc:postgresql://localhost:5432/inventory_db}
    username: ${INVENTORY_DB_USER:dbuser}
    password: ${INVENTORY_DB_PASSWORD:12345}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  sql:
    init:
      mode: never
