-- The course SQL was not included in the supplied repository. This schema models the required telemetry domain.
CREATE TABLE IF NOT EXISTS sensors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hub_id VARCHAR(255) NOT NULL,
    device_id VARCHAR(255) NOT NULL,
    type VARCHAR(32) NOT NULL,
    UNIQUE (hub_id, device_id)
);
CREATE TABLE IF NOT EXISTS scenarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hub_id VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    UNIQUE (hub_id, name)
);
CREATE TABLE IF NOT EXISTS conditions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scenario_id BIGINT NOT NULL REFERENCES scenarios(id) ON DELETE CASCADE,
    sensor_id BIGINT NOT NULL REFERENCES sensors(id),
    type VARCHAR(32) NOT NULL,
    operation VARCHAR(32) NOT NULL,
    condition_value INTEGER
);
CREATE TABLE IF NOT EXISTS actions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scenario_id BIGINT NOT NULL REFERENCES scenarios(id) ON DELETE CASCADE,
    sensor_id BIGINT NOT NULL REFERENCES sensors(id),
    type VARCHAR(32) NOT NULL,
    action_value INTEGER
);
CREATE INDEX IF NOT EXISTS conditions_scenario_idx ON conditions(scenario_id);
CREATE INDEX IF NOT EXISTS conditions_sensor_idx ON conditions(sensor_id);
CREATE INDEX IF NOT EXISTS actions_scenario_idx ON actions(scenario_id);
CREATE INDEX IF NOT EXISTS actions_sensor_idx ON actions(sensor_id);
